import type { PagoRecurrente } from '@/types/recurrentes'

export const PAGOS_RECURRENTES: PagoRecurrente[] = [
  // ── Suscripciones confirmadas ──────────────────────────────────────────
  {
    id: 'claude',
    nombre: 'Claude (Anthropic)',
    monto: 20.00,
    dia_cobro: 6,
    categoria: 'suscripcion',
    estado: 'confirmado',
    fechas_registradas: ['2026-01-07', '2026-02-06'],
  },
  {
    id: 'netflix',
    nombre: 'Netflix',
    monto: 13.99,
    dia_cobro: 10,
    categoria: 'suscripcion',
    estado: 'confirmado',
    fechas_registradas: ['2026-02-03', '2026-03-10'],
  },
  {
    id: 'playstation-network',
    nombre: 'PlayStation Network',
    monto: 7.99,
    dia_cobro: 25,
    categoria: 'suscripcion',
    estado: 'confirmado',
    fechas_registradas: ['2026-01-26', '2026-02-25'],
  },
  {
    id: 'google-one',
    nombre: 'Google One',
    monto: 3.99,
    dia_cobro: 17,
    categoria: 'suscripcion',
    estado: 'confirmado',
    fechas_registradas: ['2026-01-17', '2026-02-17'],
  },
  {
    id: 'disney-plus',
    nombre: 'Disney Plus',
    monto: 3.99,
    dia_cobro: 17,
    categoria: 'suscripcion',
    estado: 'confirmado',
    fechas_registradas: ['2026-03-17'],
    notas: '2 cobros en Mar 2026',
  },
  // ── Suscripciones posibles ─────────────────────────────────────────────
  {
    id: 'youtube-music',
    nombre: 'YouTube Music (Google)',
    monto: null,
    dia_cobro: null,
    categoria: 'suscripcion',
    estado: 'posible',
    fechas_registradas: [],
    notas: 'Aparece en historial',
  },
  {
    id: 'playstation-otro',
    nombre: 'PlayStation (otro cargo)',
    monto: null,
    dia_cobro: null,
    categoria: 'suscripcion',
    estado: 'posible',
    fechas_registradas: [],
    notas: 'Aparece en historial',
  },
  // ── Cargos bancarios automáticos (1° de cada mes) ──────────────────────
  {
    id: 'membresia',
    nombre: 'Cobro de membresía',
    monto: 2.50,
    dia_cobro: 1,
    categoria: 'cargo_bancario',
    estado: 'confirmado',
    fechas_registradas: [],
  },
  {
    id: 'seguro-fraude',
    nombre: 'Seguro de fraude mensual',
    monto: 1.00,
    dia_cobro: 1,
    categoria: 'cargo_bancario',
    estado: 'confirmado',
    fechas_registradas: [],
  },
  {
    id: 'itbms',
    nombre: 'ITBMS membresía',
    monto: 0.18,
    dia_cobro: 1,
    categoria: 'cargo_bancario',
    estado: 'confirmado',
    fechas_registradas: [],
  },
  {
    id: 'imp-seguro',
    nombre: 'Impuesto seguro fraude',
    monto: 0.05,
    dia_cobro: 1,
    categoria: 'cargo_bancario',
    estado: 'confirmado',
    fechas_registradas: [],
  },
]
